### ISSUE TITLE
Pades validation Error

### ISSUE THREAD

**Issue by MBM-TUN** [lovele0107/signature-conformance-checker#45]
Hi,
I'm getting an error when validating a Pades signature.
The same file seems to be OK on other validation checkers such as adobe and  DSS demonstration webapp
Thank you
![pades-etsi-ckecker-certs-issue](https://github.com/lovele0107/signatures-conformance-checker/assets/170734173/13bc4992-1300-481e-a786-7cb84de42707)

**Comment by jccruellas** [comment]
Good afternoon.
Thank you for using PAdESCC.
I will check and fix it, hopefully beginning next week

Juan Carlos Cruellas

**Comment by jccruellas** [comment]
Good morning, Could you please upload the PAdES signature hat you tested? 
Thanks
Juan Carlos Cruellas.

**Comment by MBM-TUN** [comment]
Hello, Thank you for your response.
I created a new file that generates the same error message.
[example-err-sig.pdf](https://github.com/lovele0107/signatures-conformance-checker/files/15456829/example-err-sig.pdf)

**Comment by jccruellas** [comment]
Good afternoon,
I would say that I have fixed the issue. I have uploaded your signature to the new deployed version and the error has dissapeared. There is a warning because the PAdESCC finds an attribute whose OID (1.2.840.113583.1.1.) it does not recognize, and it warns that it will not make any check on it. But this is a normal behaviour.

Could you please check it and let me know the results?
Also, if consider that this fixes your issue, could you please proceed to close it?

Thank you very much indeed for using PAdESCC!.
Best regards
Juan Carlos Cruellas.

**Comment by MBM-TUN** [comment]
Thank you.
Mohamed B. Mahjoubi.
